name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-static:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with: 
          target: x86_64-unknown-linux-musl
          default: true
          profile: minimal
          toolchain: stable
      - name: cache rust
        uses: Swatinem/rust-cache@v1
        with:
          key: bundled
      - name: install musl
        run: sudo apt-get update && sudo apt-get install musl musl-tools
      - name: build
        run: cargo build --release --target=x86_64-unknown-linux-musl --features=bot-utils/bundled
      - name: compress
        run: zstd -19 target/x86_64-unknown-linux-musl/debug/roll-bot
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-musl/debug/roll-bot.zst
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: login to docker registry
        if: ${{ github.event_name == 'push' && ( github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') ) }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with: 
          target: x86_64-unknown-linux-musl
          default: true
          profile: minimal
          toolchain: stable
      - name: cache rust
        uses: Swatinem/rust-cache@v1
        with:
          key: not-bundled
      - name: install musl
        run: sudo apt-get update && sudo apt-get install musl musl-tools
      - name: test
        run: cargo test --all --target=x86_64-unknown-linux-musl
      - name: build
        run: cargo build --release --target=x86_64-unknown-linux-musl
        if: ${{ github.event_name == 'push' && ( github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') ) }}
      - name: build docker image
        run: docker build --tag roll-bot .
        if: ${{ github.event_name == 'push' && ( github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') ) }}
      - name: upload docker image
        run: docker tag roll-bot ghcr.io/robinmarchart/roll-bot:latest && docker push ghcr.io/robinmarchart/roll-bot:latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      - name: upload docker image release
        run: ref={{ github.event.ref }} && tag=${ref:10} && docker tag roll-bot ghcr.io/robinmarchart/roll-bot:${tag} && docker push ghcr.io/robinmarchart/roll-bot:${tag}
        if: startsWith(github.ref, 'refs/tags/')

