name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build
        run: cargo check --all
      - name: Run tests
        run: cargo test --all
      - name: install x86_64 musl
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          override: true
      - name: install musl
        run: sudo apt-get install musl musl-tools
      - name: build static bot
        run: cargo build --release --target x86_64-unknown-linux-musl --features bot-utils/bundled
      - uses: actions/upload-artifact@v2
        with:
          name: static-roll-bot
          path: target/x86_64-unknown-linux-musl/release/roll-bot
