name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install x86_64 musl
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          override: true
      - name: run tests
        run: cargo test --all
      - name: login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: docker build --tag normal .
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: upload docker image
        run: docker tag roll-bot ghcr.io/robinmarchart/roll-bot:latest && docker push ghcr.io/robinmarchart/roll-bot:${{ steps.extract_branch.outputs.branch }}
